version: '3.1'

services:

  db:
    image: mysql-db:v0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on: 
      - db
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: my-secret-password
      PMA_HOST: db
    volumes:
     - /sessions
  app:
    depends_on:
      - db
    image: devops-flask:v0
    restart: always
    ports:
      - "5000:5000"
