apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: db
    tier: db
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
        tier: db
    spec:
      containers:
      - image: 127.0.0.1:30400/mysql-db:latest
        name: db
        ports:
        - containerPort: 3306
          name: db

