apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: phpmyadmin
    tier: phpmyadmin
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: phpmyadmin
    spec:
      containers:
      - image: 127.0.0.1:30400/phpmyadmin:latest
        name: phpmyadmin
        ports:
        - containerPort: 80
          name: phpmyadmin
